notifications:
  email: false

language: generic

sudo: required

services:
  - docker

script:
  - ./build\ image
  - ./build\ toolchain

  # Test toolchain readable.
  - toolchain=($TRAVIS_BUILD_DIR/*.tar.xz);
    [[ -r $toolchain ]]

  # Test toolchain contains required files.
  - |
    files=$(tar tf "$toolchain")
    patterns=(
      /cc1
      /cc1plus
      -uclibc-gcc
      -uclibc-g++
      /utmpx.h # Needed for Busybox/Coreutils
    )
    for pattern in "${patterns[@]}"; do
      grep -- "$pattern$" <<<"$files" || exit # Todo: find a better way to fail
    done
